### ISSUE TITLE
Can't compile with glibc >= 2.31

### ISSUE THREAD

**Issue by klausenbusk** [RIPE-NCC/ripe-atlas-probe-busybox#2]
I'm trying to build it on Arch Linux with glibc 2.32 and it fails with:
```
==========
/usr/bin/ld: debianutils/lib.a(mktemp.o): in function `mktemp_main':
mktemp.c:(.text.mktemp_main+0xa2): warning: the use of `mktemp' is dangerous, better use `mkstemp' or `mkdtemp'
/usr/bin/ld: networking/lib.a(httpget.o): in function `httpget_main':
httpget.c:(.text.httpget_main+0x1469): undefined reference to `stime'
/usr/bin/ld: networking/lib.a(httppost.o): in function `httppost_main':
httppost.c:(.text.httppost_main+0x136b): undefined reference to `stime'
/usr/bin/ld: coreutils/lib.a(date.o): in function `date_main':
date.c:(.text.date_main+0x2a0): undefined reference to `stime'
collect2: error: ld returned 1 exit status
Note: if build needs additional libraries, put them in CONFIG_EXTRA_LDLIBS.
Example: CONFIG_EXTRA_LDLIBS="pthread dl tirpc audit pam"
make: *** [Makefile:718: busybox_unstripped] Error 1
```
This has been fixed upstream in: https://git.busybox.net/busybox/commit/?id=d3539be8f27b8cbfdfee460fe08299158f08bcd9

**Comment by PhilipHomburg** [comment]
This should be fixed in the devel branch. Could you please try that?

**Comment by klausenbusk** [comment]
It indeed is, sorry for the noise :)
